version: '3'

services:
  blog-notifications:
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: ./entrypoint.sh
    image: blog-notifications:latest
    environment:
      SONAR_PASSWORD: ${SONAR_PASSWORD}
      SONAR_LOGIN: ${SONAR_LOGIN}
      SONAR_PROJECT_KEY: ${SONAR_PROJECT_KEY}
      SONAR_SERVER_URL: ${SONAR_SERVER_URL}
      BLOG_NOTIFICATIONS_PORT: ${BLOG_NOTIFICATIONS_PORT}
      NODE_ENV: ${NODE_ENV}
      SENTRY_DSN: ${SENTRY_DSN}
      DB_DEFAULT_BLOG_NOTIFICATIONS_TYPE: ${DB_DEFAULT_BLOG_NOTIFICATIONS_TYPE}
      DB_DEFAULT_BLOG_NOTIFICATIONS_HOST: ${DB_DEFAULT_BLOG_NOTIFICATIONS_HOST}
      DB_DEFAULT_BLOG_NOTIFICATIONS_PORT: ${DB_DEFAULT_BLOG_NOTIFICATIONS_PORT}
      DB_DEFAULT_BLOG_NOTIFICATIONS_USERNAME: ${DB_DEFAULT_BLOG_NOTIFICATIONS_USERNAME}
      DB_DEFAULT_BLOG_NOTIFICATIONS_PASSWORD: ${DB_DEFAULT_BLOG_NOTIFICATIONS_PASSWORD}
      DB_DEFAULT_BLOG_NOTIFICATIONS_DATABASE: ${DB_DEFAULT_BLOG_NOTIFICATIONS_DATABASE}
      DB_SECONDARY_BLOG_NOTIFICATIONS_TYPE: ${DB_SECONDARY_BLOG_NOTIFICATIONS_TYPE}
      DB_SECONDARY_BLOG_NOTIFICATIONS_HOST: ${DB_SECONDARY_BLOG_NOTIFICATIONS_HOST}
      DB_SECONDARY_BLOG_NOTIFICATIONS_PORT: ${DB_SECONDARY_BLOG_NOTIFICATIONS_PORT}
      DB_SECONDARY_BLOG_NOTIFICATIONS_USERNAME: ${DB_SECONDARY_BLOG_NOTIFICATIONS_USERNAME}
      DB_SECONDARY_BLOG_NOTIFICATIONS_PASSWORD: ${DB_SECONDARY_BLOG_NOTIFICATIONS_PASSWORD}
      DB_SECONDARY_BLOG_NOTIFICATIONS_DATABASE: ${DB_SECONDARY_BLOG_NOTIFICATIONS_DATABASE}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    ports:
      - "${BLOG_NOTIFICATIONS_PORT}:${BLOG_NOTIFICATIONS_PORT}"
    container_name: blog-notifications
    networks:
      - kong-net
    volumes:
      - .:/home/node/app

networks:
  kong-net:
    external: true
